/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
        
export default function Menhir(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/menhir.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.28, 0, 0,]} >
      <mesh geometry={nodes.Mesh_slice.geometry} material={nodes.Mesh_slice.material} />
      <mesh geometry={nodes.Mesh_slice_1.geometry} material={nodes.Mesh_slice_1.material} />
      <mesh geometry={nodes.Mesh_slice_2.geometry} material={nodes.Mesh_slice_2.material} />
      <mesh geometry={nodes.Mesh_slice_3.geometry} material={nodes.Mesh_slice_3.material} />
      <mesh geometry={nodes.Mesh_slice_4.geometry} material={nodes.Mesh_slice_4.material} />
      <mesh geometry={nodes.Mesh_slice_5.geometry} material={nodes.Mesh_slice_5.material} />
      <mesh geometry={nodes.Mesh_slice_6.geometry} material={nodes.Mesh_slice_6.material} />
      </group>
      <group position={[-0.14, 0, -0.24,]} rotation={[0, -Math.PI / 3, 0,]} >
      <mesh geometry={nodes.Mesh_slice.geometry} material={nodes.Mesh_slice.material} />
      <mesh geometry={nodes.Mesh_slice_1.geometry} material={nodes.Mesh_slice_1.material} />
      <mesh geometry={nodes.Mesh_slice_2.geometry} material={nodes.Mesh_slice_2.material} />
      <mesh geometry={nodes.Mesh_slice_3.geometry} material={nodes.Mesh_slice_3.material} />
      <mesh geometry={nodes.Mesh_slice_4.geometry} material={nodes.Mesh_slice_4.material} />
      <mesh geometry={nodes.Mesh_slice_5.geometry} material={nodes.Mesh_slice_5.material} />
      <mesh geometry={nodes.Mesh_slice_6.geometry} material={nodes.Mesh_slice_6.material} />
      </group>
      <group position={[0.14, 0, -0.24,]} rotation={[Math.PI, -Math.PI / 3, Math.PI,]} >
      <mesh geometry={nodes.Mesh_slice.geometry} material={nodes.Mesh_slice.material} />
      <mesh geometry={nodes.Mesh_slice_1.geometry} material={nodes.Mesh_slice_1.material} />
      <mesh geometry={nodes.Mesh_slice_2.geometry} material={nodes.Mesh_slice_2.material} />
      <mesh geometry={nodes.Mesh_slice_3.geometry} material={nodes.Mesh_slice_3.material} />
      <mesh geometry={nodes.Mesh_slice_4.geometry} material={nodes.Mesh_slice_4.material} />
      <mesh geometry={nodes.Mesh_slice_5.geometry} material={nodes.Mesh_slice_5.material} />
      <mesh geometry={nodes.Mesh_slice_6.geometry} material={nodes.Mesh_slice_6.material} />
      </group>
      <group position={[0.28, 0, 0,]} rotation={[-Math.PI, 0, -Math.PI,]} >
      <mesh geometry={nodes.Mesh_slice.geometry} material={nodes.Mesh_slice.material} />
      <mesh geometry={nodes.Mesh_slice_1.geometry} material={nodes.Mesh_slice_1.material} />
      <mesh geometry={nodes.Mesh_slice_2.geometry} material={nodes.Mesh_slice_2.material} />
      <mesh geometry={nodes.Mesh_slice_3.geometry} material={nodes.Mesh_slice_3.material} />
      <mesh geometry={nodes.Mesh_slice_4.geometry} material={nodes.Mesh_slice_4.material} />
      <mesh geometry={nodes.Mesh_slice_5.geometry} material={nodes.Mesh_slice_5.material} />
      <mesh geometry={nodes.Mesh_slice_6.geometry} material={nodes.Mesh_slice_6.material} />
      </group>
      <group position={[0.14, 0, 0.24,]} rotation={[-Math.PI, Math.PI / 3, -Math.PI,]} >
      <mesh geometry={nodes.Mesh_slice.geometry} material={nodes.Mesh_slice.material} />
      <mesh geometry={nodes.Mesh_slice_1.geometry} material={nodes.Mesh_slice_1.material} />
      <mesh geometry={nodes.Mesh_slice_2.geometry} material={nodes.Mesh_slice_2.material} />
      <mesh geometry={nodes.Mesh_slice_3.geometry} material={nodes.Mesh_slice_3.material} />
      <mesh geometry={nodes.Mesh_slice_4.geometry} material={nodes.Mesh_slice_4.material} />
      <mesh geometry={nodes.Mesh_slice_5.geometry} material={nodes.Mesh_slice_5.material} />
      <mesh geometry={nodes.Mesh_slice_6.geometry} material={nodes.Mesh_slice_6.material} />
      </group>
      <group position={[-0.14, 0, 0.24,]} rotation={[0, Math.PI / 3, 0,]} >
      <mesh geometry={nodes.Mesh_slice_7.geometry} material={nodes.Mesh_slice_7.material} />
      <mesh geometry={nodes.Mesh_slice_8.geometry} material={nodes.Mesh_slice_8.material} />
      <mesh geometry={nodes.Mesh_slice_9.geometry} material={nodes.Mesh_slice_9.material} />
      <mesh geometry={nodes.Mesh_slice_10.geometry} material={nodes.Mesh_slice_10.material} />
      <mesh geometry={nodes.Mesh_slice_11.geometry} material={nodes.Mesh_slice_11.material} />
      <mesh geometry={nodes.Mesh_slice_12.geometry} material={nodes.Mesh_slice_12.material} />
      <mesh geometry={nodes.Mesh_slice_13.geometry} material={nodes.Mesh_slice_13.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/menhir.gltf')